### ISSUE TITLE
angles of torque zero mode is not correct in gravity_compensated_mode.py 

### ISSUE THREAD

**Issue by StanleyYake** [Kinovarobotics/kinova-ros#331] opened 2021-03-17 02:15 UTC
Hello there, I found angles of torque zero mode is differ in gravity_compensated_mode.py in KINOVA MAINTENANCE GUIDE.pdf which refer to [180,180,180,180, 0, 90] candle like position, but the gravity_compensated_mode.py refers to [180, 180,180,180,180,180]. Are we is only start from a candle like position and set torque zero command not reset torque sensor?
![微信图片_20210317101204](https://user-images.githubusercontent.com/7522853/111404387-a35a6d80-8709-11eb-87d6-794242aba49d.png)

https://github.com/Kinovarobotics/kinova-ros/blob/38293ed73bc230e9ca7e7312fc268736821fd9cc/kinova_demo/nodes/kinova_demo/gravity_compensated_mode.py#L32

**Comment by YangSai567** [comment] 2021-04-12 08:12
Hi, I found that as same as you.First. I only have JACO SDK, should that be able to reset torque control mode? Then, do you have ideals of starting gravity compensated mode? Thanks!

**Comment by felixmaisonneuve** [comment] 2021-05-31 17:59
Hi @StanleyYake,
Effectively, angles differ. 
However, gravity_compensated_mode.py does not reset the torque sensors, which means values could be anything. The objective being only to show what happens when all torques values are set to 0. 
Also, spherical and non-spherical wrist to not operate the same way, it is possible (not sure, I haven't verified) that 180 instead of 0 is a candle-like position for the spherical wrist. It might also be a typo, but then again, it doesn't really change anything. 

To answer to @YangSai567, yes, you can reset torque control settings in JACO-SDK.  You can access actuator angles in Monitoring section and you can set zero torque sensor in Advanced Settings. I am not sure what you mean by "ideals of starting gravity compensated mode".

**Comment by felixmaisonneuve** [comment] 2021-06-01 15:09
Also @StanleyYake, where did you find the maintenance guide you mentionned? I am not sure where this screenshot comes from. 
The user guide for Jaco2 available on Kinova's website recommend these values :
![image](https://user-images.githubusercontent.com/83971099/120345575-97be2200-c2c8-11eb-8281-31b94c4e317e.png)


I also had confirmation that the arm position when reseting torque is not very important. It is recommended to put the arm in a candle-like position to reduce the effect on gravity on the sensors. Reseting the arm while it is in a horizontal position might affect calibration because of cross-torque (caused by gravity) on the joints, but it is possible to do so.

**Comment by felixmaisonneuve** [comment] 2021-07-26 19:16
Hi @StanleyYake,

I will assume your question was answered and close this issue. If you still have a problem, feel free to re-open or create a new issue.

Thank you,
Felix

**Closed by felixmaisonneuve** 2021-07-26 19:16 UTC
