### ISSUE TITLE
Mico does not go to Torque control Mode 

### ISSUE THREAD

**Issue by alireza-zen** [Kinovarobotics/kinova-ros#351] opened 2021-08-26 02:18 UTC
## Description

We have m1n6s200 and m1n6s300 at our lab. I am trying to switch to torque control mode but I had no success. I checked other similar issues like #336 . In the same way I move mico to candle like position, I set torques to zero. But after that I have no success in switching to torque mode. I have tried switching with the Torque console, API and service call (with kinova bring up), but I could not make it work. It does show "Switching to torque control" without errors usually, but I can not command torques to the robot using the /m1n6s200_driver/in/joint_torque or the API

## Version

ROS distribution : Melodic

Branch and commit you are using : Melodic-devel

## Steps to reproduce

1. Moving the robot to candle like position via the code written below and setting the torques to zero
2. putting the zeroTorqueControlSafetyFactor(1)
3. Setting setTorqueControlState(1)
4. setJointTorques(joint_torques) which joint_torques is --> float joint_torques[6]={4,0,0,0,0,0};

I have tried doing the same thing with the service call as well.
1. Moving to the candle position with the previous code and killing the node
2. roslaunch kinova_bringup kinova_robot.launch 
3. rosservice call /m1n6s200_driver/in/set_zero_torques ( I see "Torques for all joints set to zero")
4. rosservice call /m1n6s200_driver/in/set_torque_control_mode "state: 1" ( I see "Switching to torque control")
5. giving values to /m1n6s200_driver/in/joint_torque topic through rqt

## Code example (if necessary)
The code for moving to candle position, making the torques zero and commanding torques. The sleep part was just to make sure that mico would have enough time in case it needs. (I guess we do not need the while loop, am I right? I tried without it too) 
```
#include<ros/ros.h>
#include<kinova_driver/kinova_ros_types.h>
#include<kinova_driver/kinova_joint_angles_action.h>
#include<iostream>

#define robot_type "m1n6s200"
#define TORQUE 1
#define POSITION 0

int main(int argc,char** argv)
{
    ros::init(argc,argv,"kinova_test");
    ros::NodeHandle n;
    ros::Duration loop(10);
    
    
    boost::recursive_mutex api_mutex;
    kinova::KinovaAPI api;
    kinova::KinovaComm mico(n,api_mutex,1,robot_type);
    kinova::KinovaAngles candle_position,read_torques;


    api.initializeKinovaAPIFunctions(kinova::KinovaAPIType::USB);
    mico.startAPI();   
    candle_position.InitStruct();

    // Defining the candle position
    candle_position.Actuator1 =0;
    candle_position.Actuator2 =180;
    candle_position.Actuator3 = 180;
    candle_position.Actuator4 = 0;
    candle_position.Actuator5 = 0;
    candle_position.Actuator6 = 180;
    
    // Defining the join torques
    float joint_torques[6]={4,0,0,0,0,0};

    mico.setJointAngles(candle_position,20,20,0,true);
    loop.sleep();
    mico.setZeroTorque();
    std::cout<<"Setting torques to zero" <<std::endl;
    loop.sleep();



    mico.setToquesControlSafetyFactor(1);
    mico.SetTorqueControlState(TORQUE);
    mico.setJointTorques(joint_torques);

    while(ros::ok())
    {      
        mico.setJointTorques(joint_torques);
        mico.getJointTorques(read_torques);
        std::cout<<"The torque for the first actuator is  "<<read_torques.Actuator1<<std::endl;
    }
}    
```

## Expected behavior

Mico moves to torque control mode and accepts torque commands.

**Comment by alireza-zen** [comment] 2021-08-26 11:22
So I could make the m1n6s300 one work (through the service call, and the torque console), but the other one still does not work. What I realized is that the m1n6s300 one was on "service mode" when I launched kinova_robot.launch while the one that does not work says it is on assistive mode. Does this make any difference? If yes, would you mind letting me know how I can switch these modes? 
One other thing that I noticed, is that the torque readings from m1n6s200 one (the one that does not work) do not seem realistic; I mean, when it is at a certain position, if I push it with my hands the torque readings would still stay 0, while with the other robot that works properly, the torque sensors values change when I apply external force to the manipulator while it is at a constant position.

**Comment by felixmaisonneuve** [comment] 2021-08-26 13:51
Hi @AlirezaMsb,

It is recommended to change your arm in service mode. In the folder that contains Development Center, you can findexecutables to change between assistive and service mode can be found within that folder. They are located in *JACO-SDK/RobotConfiguration/*. 

For the torque control mode, I'm glad you managed to make one arm work. Some of the Mico arm do not have torque sensors, so it is not possible to put them in torque control mode. I suspect it is the case here, which would explain your torque readings. 

I would try to put your arm in service to see if it is different, but I think your arm does not have torque sensors.

Regards,
Felix

**Comment by alireza-zen** [comment] 2021-08-27 02:55
@felixmaisonneuve  
Thank you for your reply Felix,
Following up on our discussion, I changed the arm to service mode and now the torque sensors give realistic data. I can launch the admittance control on it from the development center and the service call now, and it works well. But I still can not move it to torque control mode. I find my issue similar to #336 . I followed the steps that you have mentioned there:

    1.Put your arm in candle-like position (every joint in a vertical position)
    2.Open Development Center (JacoSDK). In the "Monitoring" section, every actuator should have a value close to 180° in the
       Command and Position columns. Every actuator should also have a Torque value between -10 Nm and 10 Nm.
    3.Open "Advanced Settings". In the section "Torque zero", select "apply to all". The "Monitoring" section should now show
       Torque values close to 0 for each actuator.
    4. Open TorqueConsole.
    5. Test your connection with the "Test Connection" button. It should change to "Good Connection"
    6. Change the "Safety Factor" to 1
    7. Click "Switch Torque Control" button.

The only difference for me is that the name of the folder is MICO-SDK by default (in case that makes any difference). 
When I use the service call to activate the torque control, I get no errors, and in the terminal it says "Switching to torque control
'' too. 

The other mico is working properly now though, and today switched to torque control mode whenever I tried it. 

About what you mentioned, actually this is the older mico that does not work properly (has been bought in 2014). Is it possible that it does not support torque control, and if yes, is there any way that I can make sure that is the case? 

Also, something that I have noticed is that the torque readings are not that exact, for example in the home pose when I launch the torque reading code from the development center I get the following results (after running the COM parameter estimation):

Actuator 1   torque : -0.108195 N*m     without gravity : -0.108195 N*m
Actuator 2   torque : -2.83367 N*m     without gravity : 0.0221965 N*m
Actuator 3   torque : 3.77894 N*m     without gravity : 0.162986 N*m
Actuator 4   torque : -1.16303 N*m     without gravity : 0.0321279 N*m
Actuator 5   torque : -0.193794 N*m     without gravity : 0.0309581 N*m
Actuator 6   torque : -0.0305785 N*m     without gravity : -0.0305785 N*m
Actuator 7   torque : -7.19879e-37 N*m     without gravity : -9.01736e-37 N*m

Shouldn't the "without gravity" terms be closer to zero (mainly considering the third joint)?

**Comment by felixmaisonneuve** [comment] 2021-08-27 14:41
Hi @AlirezaMsb,

It is possible that your arm does not support torque control. I will talk to someone next week (he's on vacation right now) to see if it is the case. We probably have a list of all the Mico arms that support torque control or something like that. I will need your arm identification number. 

For your torque readings, I think they look pretty good. To me, they are already pretty close to 0. 

Regards,
Felix

**Comment by alireza-zen** [comment] 2021-08-29 02:40
@felixmaisonneuve 
Hey Felix,

Thank you for your kind follow up on this issue, 
I'll send the identification number here tomorrow then. 
As for the torque readings, I'm happy to hear that, as the value of the third joint seemed a bit suspicious to me (it was originally around 0.5N.m, it decreased after I ran the COM parameter estimation).

Again thank you for your help.

**Comment by AlirezaMsb** [comment] 2021-08-30 06:09
@felixmaisonneuve 
Hey Felix, 
I checked our document and unfortunately I could not find the serial number. When I launch from kinova_bringup, for the serial number it shows "not set", I guess the firmware of the robot might have been updated without resetting the serial number. Is there any other way that I can find the serial number? 
The purchase was done on "2014/08/26". As for the purchase information I guess the other mico serial number might be helpful ( "PJ00650019433597-0"). I apologize for the problem.

As for our discussion, something that I noticed is that when I switch the old mico from assistive to service mode I get a segmentation fault:

Executing service robotics configuration conversion program...
I N I T I A L I Z A T I O N   C O M P L E T E D

Scanning the USB bus...

Found a robot on the USB bus (Not Set)
MICO detected, switching to service configuration.

C L O S I N G   A P I
Segmentation fault (core dumped)

While when I switch to assistive mode there is no such a thing:

Executing assistive robotics configuration conversion program...
I N I T I A L I Z A T I O N   C O M P L E T E D

Scanning the USB bus...

Found a robot on the USB bus (Not Set)
MICO detected, switching to assistive configuration.

C L O S I N G   A P I

Application was executed correctly and 1 device(s) has been modified.
Press any key to exit application. 

Is that natural?

**Comment by alireza-zen** [comment] 2021-08-30 07:18
@felixmaisonneuve 
Hey Felix, 
The serial number for this mico is: ( "PJ-0065-0001-14211-0001"). I apologize for the problem. If there is anything that I can help you with please let me know. 

As for our discussion, something that I noticed is that when I switch the old mico from assistive to service mode I get a segmentation fault:
> 
> Executing service robotics configuration conversion program...
> I N I T I A L I Z A T I O N   C O M P L E T E D
> 
> Scanning the USB bus...
> 
> Found a robot on the USB bus (Not Set)
> MICO detected, switching to service configuration.
> 
> C L O S I N G   A P I
> Segmentation fault (core dumped)

While when I switch to assistive mode there is no such a thing:


> Executing assistive robotics configuration conversion program...
> I N I T I A L I Z A T I O N   C O M P L E T E D
> 
> Scanning the USB bus...
> 
> Found a robot on the USB bus (Not Set)
> MICO detected, switching to assistive configuration.
> 
> C L O S I N G   A P I
> 
> Application was executed correctly and 1 device(s) has been modified.
> Press any key to exit application. 



However, after switching to service mode, it shows that it is in the service mode when I launch kinova_robot.launch and I can read the torque values from the joints; is the error natural?

**Comment by felixmaisonneuve** [comment] 2021-08-30 16:02
Hi @AlirezaMsb,

Your robot has torque sensors and should be able to go into torque control mode. The problem is coming from somewhere else. 
There is 2 things I need you to check. 
1. What are your firmware versions (for your base and actuators). In Development Center, go to *Generale Settings*->*Updates*. Then take a screenshot of your versions. Your atuators should be at 1.5.1 or highier and it should say the arm is in service mode (in arm type). You could also compare with your working arm to see if versions match. Also, the latest main firmware version is 6.2.8, so it is possible we will need to update it, but I am not sure if it is necessary for torque control mode to work (wich is why I want to compare with your other arm)
2. When you put your arm in candle-like position and you reset your torque, what are the torque values?  I have to mentionned you cannot use ROS and Development Center at the same time. So you can either use ROS and echo the topic with torque sensor values after `setZeroTorques()`, or use Development Center in *Monitoring* Section to check torque values after setting 0 torques (in *Advanced Settings* or by using TorqueConsole). All joints should have a torque close to 0. Otherwise your arm won't change to torque control mode.

Let me know how it goes,
Felix

**Comment by felixmaisonneuve** [comment] 2021-08-30 19:14
Also, about the segmentation fault, it happens after the "CLOSING API" line and your arm seems to have correctly changed to service mode, so I think everything should be good.

**Comment by alireza-zen** [comment] 2021-08-31 02:17
@felixmaisonneuve 
Thank you for your kind reply Felix,
I think what you mentioned in your first point is not the case for the older mico. 
Here's the screenshot for the older mico (sorry that it does not show the name of the actuators, etc properly)
![Screenshot from 2021-08-31 11-09-06](https://user-images.githubusercontent.com/35629121/131431292-5b435826-9984-4858-a1a1-412e493b6d60.png)


The actuators are not 1.5.1 or higher. While for the newer mico that is the case (the following picture):
![Screenshot from 2021-08-31 11-11-22](https://user-images.githubusercontent.com/35629121/131431310-5ddf8070-5a3c-4c7e-93ed-06c4f259ed16.png)


I will try updating the firmware on the first mico then, and see the results! 

As for the second point that you mentioned, that is what I do too. The torque readings both from the terminal (If I use ros), and from the Development center are close to zero. 
![Screenshot from 2021-08-31 11-31-08](https://user-images.githubusercontent.com/35629121/131432250-a251dfe8-bb1c-45b3-9d42-295ebc7062c6.png)

**Comment by alireza-zen** [comment] 2021-08-31 02:58
I tried updating the older mico with the firmware in the following website but even after the update the versions are still the same:

https://www.kinovarobotics.com/en/knowledge-hub/mico-robotic-arm

Should I try updating it with another firmware?

**Comment by felixmaisonneuve** [comment] 2021-08-31 14:54
Hi @AlirezaMsb,

This is where the problem is coming from. Your actuator versions are too old. They cannot be changed manually and you will need to send the arm to Kinovato update them (if you want too). You will need to send an email to support@kinova.ca explaining your situation and they will take it from there. 

Unfortunately, I cannot help you any more, so I will close this issue.

Sorry for the inconveniance,
Felix

**Closed as completed by felixmaisonneuve** 2021-08-31 14:54 UTC

**Comment by alireza-zen** [comment] 2021-09-02 02:42
@felixmaisonneuve 
Hey Felix,
Sorry for my late reply,
I understand, we will send an email in case we decided to do so then. 
Thank you very much for your help though! I very much appreciate it.
