### ISSUE TITLE
Is there  a way to change the topic pulish rate of joint_state and tool_pose?

### ISSUE THREAD

**Issue by lienbo** [Kinovarobotics/kinova-ros#280] opened 2019-10-27 04:15 UTC
## Summary
I use rostopic hz /.../.../...tool_pose  and /.../.../.../joint_state
and the default publish rate is 10hz . So how to change the rate to100hz, as I want to use these msgs to control robot in Cartesian space velocity control,which need 100hz. 
A short description of the requested feature.

## Use case

Why is this feature needed?

What are the use case covered by this feature?

## Alternative

Do you have an idea how on how best to implement this enhancement?

If this feature is not implemented, do you have a workaround?

## Possible issues

Anything that could be affected by the new feature.

## Additional context

Any other information you would like us to know about the requested enhancement.

**Comment by alexvannobel** [comment] 2019-11-01 18:07
Hi @lienbo ,
As this is a duplicate of #281 , I'll close this issue and answer in the other issue.
Best,
Alex

**Closed by alexvannobel** 2019-11-01 18:07 UTC
